"""initial_schema

Revision ID: 49caac037caf
Revises: 
Create Date: 2025-12-19 15:35:04.056197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49caac037caf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', postgresql.ENUM('CONTRACTOR', 'CLIENT', 'WORKER', 'SUBCONTRACTOR', name='user_role_enum'), nullable=False),
    sa.Column('zulip_user_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("email ~* '^[A-Za-z0-9._%%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'", name='users_email_valid'),
    sa.CheckConstraint('LENGTH(id) > 0 AND LENGTH(id) <= 50', name='users_id_length'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_zulip_user_id', 'users', ['zulip_user_id'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('role', postgresql.ENUM('CONTRACTOR', 'CLIENT', 'ARCHITECT', 'VIEWER', 'SUBCONTRACTOR', name='project_member_role_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_members_project_user')
    )
    op.create_index('idx_project_members_project', 'project_members', ['project_id'], unique=False)
    op.create_index('idx_project_members_project_role', 'project_members', ['project_id', 'role'], unique=False)
    op.create_index('idx_project_members_role', 'project_members', ['role'], unique=False)
    op.create_index('idx_project_members_user', 'project_members', ['user_id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'SENT', 'APPROVED', 'REJECTED', 'SUPERSEDED', name='quote_status_enum'), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('LENGTH(id) > 0 AND LENGTH(id) <= 50', name='quotes_id_length'),
    sa.CheckConstraint('version_number > 0', name='quotes_version_positive'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quotes_created', 'quotes', ['created_at'], unique=False)
    op.create_index('idx_quotes_project', 'quotes', ['project_id'], unique=False)
    op.create_index('idx_quotes_project_status', 'quotes', ['project_id', 'status'], unique=False)
    op.create_index('idx_quotes_status', 'quotes', ['status'], unique=False)
    op.alter_column('approvals', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('approvals', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=postgresql.ENUM('APPROVED', 'REJECTED', 'CHANGE_ORDER', 'PENDING', 'SUPPLIED_BY', name='approval_status_enum'),
               existing_nullable=True)
    op.alter_column('comments', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.add_column('edit_history', sa.Column('user_id', sa.String(length=50), nullable=True))
    op.alter_column('edit_history', 'source',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.create_index('idx_edit_history_user', 'edit_history', ['user_id'], unique=False)
    op.create_foreign_key(None, 'edit_history', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('items', 'labor_type',
               existing_type=sa.VARCHAR(length=50),
               type_=postgresql.ENUM('DEMOLITION', 'STRUCTURAL', 'FACADE', 'EXTERIOR_JOINERY', 'PLASTERING', 'PLUMBING', 'ELECTRICAL', 'WALL_COVERING', 'INTERIOR_JOINERY', 'LANDSCAPING', 'PRICE_REVISION', name='work_type_enum'),
               existing_nullable=True)
    op.create_index('idx_items_labor_type', 'items', ['labor_type'], unique=False)
    op.alter_column('orders', 'delivery_status',
               existing_type=sa.VARCHAR(length=50),
               type_=postgresql.ENUM('PENDING', 'ORDERED', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='delivery_status_enum'),
               existing_nullable=True)
    op.add_column('projects', sa.Column('owner_id', sa.String(length=50), nullable=False))
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=postgresql.ENUM('DRAFT', 'READY', 'ACTIVE', 'COMPLETED', 'ARCHIVED', name='project_status_enum'),
               existing_nullable=False)
    op.create_index('idx_projects_owner', 'projects', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('projects', 'client_name')
    op.drop_column('projects', 'devis_status')
    op.add_column('worker_jobs', sa.Column('project_id', sa.String(length=50), nullable=False))
    op.add_column('worker_jobs', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('worker_jobs', sa.Column('comment', sa.Text(), nullable=True))
    op.alter_column('worker_jobs', 'job_type',
               existing_type=sa.VARCHAR(length=50),
               type_=postgresql.ENUM('DEMOLITION', 'STRUCTURAL', 'FACADE', 'EXTERIOR_JOINERY', 'PLASTERING', 'PLUMBING', 'ELECTRICAL', 'WALL_COVERING', 'INTERIOR_JOINERY', 'LANDSCAPING', 'PRICE_REVISION', name='work_type_enum'),
               existing_nullable=True)
    op.drop_index('idx_worker_jobs_chantier', table_name='worker_jobs')
    op.create_index('idx_worker_jobs_location', 'worker_jobs', ['location'], unique=False)
    op.create_index('idx_worker_jobs_project', 'worker_jobs', ['project_id'], unique=False)
    op.create_index('idx_worker_jobs_type', 'worker_jobs', ['job_type'], unique=False)
    op.drop_constraint('worker_jobs_worker_id_fkey', 'worker_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'worker_jobs', 'workers', ['worker_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'worker_jobs', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('worker_jobs', 'chantier_name')
    op.add_column('workers', sa.Column('user_id', sa.String(length=50), nullable=False))
    op.add_column('workers', sa.Column('certificates', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('idx_workers_name', table_name='workers')
    op.create_index('idx_workers_certificates', 'workers', ['certificates'], unique=False, postgresql_using='gin')
    op.create_foreign_key(None, 'workers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('workers', 'id')
    op.drop_column('workers', 'email')
    op.drop_column('workers', 'phone')
    op.drop_column('workers', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('workers', sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('workers', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('workers', sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workers', type_='foreignkey')
    op.drop_index('idx_workers_certificates', table_name='workers', postgresql_using='gin')
    op.create_index('idx_workers_name', 'workers', ['name'], unique=False)
    op.drop_column('workers', 'certificates')
    op.drop_column('workers', 'user_id')
    op.add_column('worker_jobs', sa.Column('chantier_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'worker_jobs', type_='foreignkey')
    op.drop_constraint(None, 'worker_jobs', type_='foreignkey')
    op.create_foreign_key('worker_jobs_worker_id_fkey', 'worker_jobs', 'workers', ['worker_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_worker_jobs_type', table_name='worker_jobs')
    op.drop_index('idx_worker_jobs_project', table_name='worker_jobs')
    op.drop_index('idx_worker_jobs_location', table_name='worker_jobs')
    op.create_index('idx_worker_jobs_chantier', 'worker_jobs', ['chantier_name'], unique=False)
    op.alter_column('worker_jobs', 'job_type',
               existing_type=postgresql.ENUM('DEMOLITION', 'STRUCTURAL', 'FACADE', 'EXTERIOR_JOINERY', 'PLASTERING', 'PLUMBING', 'ELECTRICAL', 'WALL_COVERING', 'INTERIOR_JOINERY', 'LANDSCAPING', 'PRICE_REVISION', name='work_type_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('worker_jobs', 'comment')
    op.drop_column('worker_jobs', 'location')
    op.drop_column('worker_jobs', 'project_id')
    op.add_column('projects', sa.Column('devis_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('client_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index('idx_projects_owner', table_name='projects')
    op.alter_column('projects', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'READY', 'ACTIVE', 'COMPLETED', 'ARCHIVED', name='project_status_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('projects', 'owner_id')
    op.alter_column('orders', 'delivery_status',
               existing_type=postgresql.ENUM('PENDING', 'ORDERED', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='delivery_status_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_index('idx_items_labor_type', table_name='items')
    op.alter_column('items', 'labor_type',
               existing_type=postgresql.ENUM('DEMOLITION', 'STRUCTURAL', 'FACADE', 'EXTERIOR_JOINERY', 'PLASTERING', 'PLUMBING', 'ELECTRICAL', 'WALL_COVERING', 'INTERIOR_JOINERY', 'LANDSCAPING', 'PRICE_REVISION', name='work_type_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_constraint(None, 'edit_history', type_='foreignkey')
    op.drop_index('idx_edit_history_user', table_name='edit_history')
    op.alter_column('edit_history', 'source',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('edit_history', 'user_id')
    op.alter_column('comments', 'role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('approvals', 'status',
               existing_type=postgresql.ENUM('APPROVED', 'REJECTED', 'CHANGE_ORDER', 'PENDING', 'SUPPLIED_BY', name='approval_status_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('approvals', 'role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index('idx_quotes_status', table_name='quotes')
    op.drop_index('idx_quotes_project_status', table_name='quotes')
    op.drop_index('idx_quotes_project', table_name='quotes')
    op.drop_index('idx_quotes_created', table_name='quotes')
    op.drop_table('quotes')
    op.drop_index('idx_project_members_user', table_name='project_members')
    op.drop_index('idx_project_members_role', table_name='project_members')
    op.drop_index('idx_project_members_project_role', table_name='project_members')
    op.drop_index('idx_project_members_project', table_name='project_members')
    op.drop_table('project_members')
    op.drop_index('idx_users_zulip_user_id', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
