"""initial_schema

Revision ID: 49caac037caf
Revises: 
Create Date: 2025-12-19 15:35:04.056197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49caac037caf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', postgresql.ENUM('CONTRACTOR', 'CLIENT', 'WORKER', 'SUBCONTRACTOR', name='user_role_enum'), nullable=False),
    sa.Column('zulip_user_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("email ~* '^[A-Za-z0-9._%%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'", name='users_email_valid'),
    sa.CheckConstraint('LENGTH(id) > 0 AND LENGTH(id) <= 50', name='users_id_length'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_zulip_user_id', 'users', ['zulip_user_id'], unique=False)
    
    # Create projects table (needed before project_members and quotes)
    op.create_table('projects',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.String(length=50), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'READY', 'ACTIVE', 'COMPLETED', 'ARCHIVED', name='project_status_enum'), nullable=False),
    sa.Column('invoice_count', sa.Integer(), nullable=False),
    sa.Column('percentage_paid', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('has_data', sa.Boolean(), nullable=False),
    sa.CheckConstraint('LENGTH(id) > 0 AND LENGTH(id) <= 50', name='projects_id_length'),
    sa.CheckConstraint('LENGTH(name) > 0 AND LENGTH(name) <= 255', name='projects_name_length'),
    sa.CheckConstraint('start_date IS NULL OR end_date IS NULL OR start_date <= end_date', name='projects_date_range_valid'),
    sa.CheckConstraint('invoice_count >= 0', name='projects_invoice_count_valid'),
    sa.CheckConstraint('percentage_paid >= 0 AND percentage_paid <= 100', name='projects_percentage_paid_valid'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_status', 'projects', ['status'], unique=False)
    op.create_index('idx_projects_created', 'projects', ['created_at'], unique=False)
    op.create_index('idx_projects_dates', 'projects', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_projects_owner', 'projects', ['owner_id'], unique=False)
    
    op.create_table('project_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('role', postgresql.ENUM('CONTRACTOR', 'CLIENT', 'ARCHITECT', 'VIEWER', 'SUBCONTRACTOR', name='project_member_role_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_members_project_user')
    )
    op.create_index('idx_project_members_project', 'project_members', ['project_id'], unique=False)
    op.create_index('idx_project_members_project_role', 'project_members', ['project_id', 'role'], unique=False)
    op.create_index('idx_project_members_role', 'project_members', ['role'], unique=False)
    op.create_index('idx_project_members_user', 'project_members', ['user_id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'SENT', 'APPROVED', 'REJECTED', 'SUPERSEDED', name='quote_status_enum'), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('LENGTH(id) > 0 AND LENGTH(id) <= 50', name='quotes_id_length'),
    sa.CheckConstraint('version_number > 0', name='quotes_version_positive'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quotes_created', 'quotes', ['created_at'], unique=False)
    op.create_index('idx_quotes_project', 'quotes', ['project_id'], unique=False)
    op.create_index('idx_quotes_project_status', 'quotes', ['project_id', 'status'], unique=False)
    op.create_index('idx_quotes_status', 'quotes', ['status'], unique=False)
    
    # Create workers table (user_id as PK)
    op.create_table('workers',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('certificates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('idx_workers_certificates', 'workers', ['certificates'], unique=False, postgresql_using='gin')
    
    # Create sections table
    op.create_table('sections',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('LENGTH(id) > 0 AND LENGTH(id) <= 50', name='sections_id_length'),
    sa.CheckConstraint('LENGTH(label) > 0 AND LENGTH(label) <= 255', name='sections_label_length'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sections_project', 'sections', ['project_id'], unique=False)
    
    # Create items table
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.String(length=50), nullable=False),
    sa.Column('product', sa.Text(), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('supplier_link', sa.Text(), nullable=True),
    sa.Column('labor_type', postgresql.ENUM('DEMOLITION', 'STRUCTURAL', 'FACADE', 'EXTERIOR_JOINERY', 'PLASTERING', 'PLUMBING', 'ELECTRICAL', 'WALL_COVERING', 'INTERIOR_JOINERY', 'LANDSCAPING', 'PRICE_REVISION', name='work_type_enum'), nullable=True),
    sa.Column('price_ttc', sa.Numeric(10, 2), nullable=True),
    sa.Column('price_ht_quote', sa.Numeric(10, 2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('LENGTH(TRIM(product)) > 0', name='items_product_not_empty'),
    sa.CheckConstraint('price_ht_quote IS NULL OR price_ht_quote >= 0', name='items_price_ht_valid'),
    sa.CheckConstraint('price_ttc IS NULL OR price_ttc >= 0', name='items_price_ttc_valid'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'product', name='uq_items_section_product')
    )
    op.create_index('idx_items_labor_type', 'items', ['labor_type'], unique=False)
    op.create_index('idx_items_product', 'items', ['product'], unique=False)
    op.create_index('idx_items_section', 'items', ['section_id'], unique=False)
    op.create_index('idx_items_updated', 'items', ['updated_at'], unique=False)
    
    # Create approvals table
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', postgresql.ENUM('APPROVED', 'REJECTED', 'CHANGE_ORDER', 'PENDING', 'SUPPLIED_BY', name='approval_status_enum'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('client', 'contractor')", name='approvals_role_valid'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'role', name='uq_approvals_item_role')
    )
    op.create_index('idx_approvals_item', 'approvals', ['item_id'], unique=False)
    op.create_index('idx_approvals_item_role', 'approvals', ['item_id', 'role'], unique=False)
    op.create_index('idx_approvals_status', 'approvals', ['status'], unique=False)
    
    # Create replacement_urls table
    op.create_table('replacement_urls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_replacement_urls_approval', 'replacement_urls', ['approval_id'], unique=False)
    
    # Create orders table
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('ordered', sa.Boolean(), nullable=False),
    sa.Column('order_date', sa.String(length=10), nullable=True),
    sa.Column('delivery_date', sa.String(length=10), nullable=True),
    sa.Column('delivery_status', postgresql.ENUM('PENDING', 'ORDERED', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='delivery_status_enum'), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity IS NULL OR quantity > 0', name='orders_quantity_valid'),
    sa.CheckConstraint("(order_date IS NULL OR order_date ~ '^\\d{2}/\\d{2}$') AND (delivery_date IS NULL OR delivery_date ~ '^\\d{2}/\\d{2}$')", name='orders_date_format'),
    sa.CheckConstraint('(ordered = FALSE AND order_date IS NULL) OR (ordered = TRUE AND order_date IS NOT NULL)', name='orders_ordered_with_date'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_index('idx_orders_item', 'orders', ['item_id'], unique=False)
    op.create_index('idx_orders_ordered', 'orders', ['ordered'], unique=False)
    
    # Create comments table
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('client', 'contractor')", name='comments_role_valid'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'role', name='uq_comments_item_role')
    )
    op.create_index('idx_comments_item', 'comments', ['item_id'], unique=False)
    
    # Create edit_history table
    op.create_table('edit_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('section_id', sa.String(length=50), nullable=True),
    sa.Column('section_label', sa.String(length=255), nullable=True),
    sa.Column('product', sa.Text(), nullable=True),
    sa.Column('field_path', sa.String(length=255), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('manual', 'agent')", name='edit_history_source_valid'),
    sa.CheckConstraint('LENGTH(field_path) > 0 AND LENGTH(field_path) <= 255', name='edit_history_field_path_length'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_edit_history_item', 'edit_history', ['item_id'], unique=False)
    op.create_index('idx_edit_history_timestamp', 'edit_history', ['timestamp'], unique=False)
    op.create_index('idx_edit_history_user', 'edit_history', ['user_id'], unique=False)
    
    # Create custom_fields table
    op.create_table('custom_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'field_name', name='uq_custom_fields_item_field')
    )
    op.create_index('idx_custom_fields_item', 'custom_fields', ['item_id'], unique=False)
    
    # Create worker_jobs table
    op.create_table('worker_jobs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('worker_id', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('job_type', postgresql.ENUM('DEMOLITION', 'STRUCTURAL', 'FACADE', 'EXTERIOR_JOINERY', 'PLASTERING', 'PLUMBING', 'ELECTRICAL', 'WALL_COVERING', 'INTERIOR_JOINERY', 'LANDSCAPING', 'PRICE_REVISION', name='work_type_enum'), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_worker_jobs_dates', 'worker_jobs', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_worker_jobs_location', 'worker_jobs', ['location'], unique=False)
    op.create_index('idx_worker_jobs_project', 'worker_jobs', ['project_id'], unique=False)
    op.create_index('idx_worker_jobs_type', 'worker_jobs', ['job_type'], unique=False)
    op.create_index('idx_worker_jobs_worker', 'worker_jobs', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('workers', sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('workers', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('workers', sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workers', type_='foreignkey')
    op.drop_index('idx_workers_certificates', table_name='workers', postgresql_using='gin')
    op.create_index('idx_workers_name', 'workers', ['name'], unique=False)
    op.drop_column('workers', 'certificates')
    op.drop_column('workers', 'user_id')
    op.add_column('worker_jobs', sa.Column('chantier_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'worker_jobs', type_='foreignkey')
    op.drop_constraint(None, 'worker_jobs', type_='foreignkey')
    op.create_foreign_key('worker_jobs_worker_id_fkey', 'worker_jobs', 'workers', ['worker_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_worker_jobs_type', table_name='worker_jobs')
    op.drop_index('idx_worker_jobs_project', table_name='worker_jobs')
    op.drop_index('idx_worker_jobs_location', table_name='worker_jobs')
    op.create_index('idx_worker_jobs_chantier', 'worker_jobs', ['chantier_name'], unique=False)
    op.alter_column('worker_jobs', 'job_type',
               existing_type=postgresql.ENUM('DEMOLITION', 'STRUCTURAL', 'FACADE', 'EXTERIOR_JOINERY', 'PLASTERING', 'PLUMBING', 'ELECTRICAL', 'WALL_COVERING', 'INTERIOR_JOINERY', 'LANDSCAPING', 'PRICE_REVISION', name='work_type_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('worker_jobs', 'comment')
    op.drop_column('worker_jobs', 'location')
    op.drop_column('worker_jobs', 'project_id')
    op.add_column('projects', sa.Column('devis_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('client_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index('idx_projects_owner', table_name='projects')
    op.alter_column('projects', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'READY', 'ACTIVE', 'COMPLETED', 'ARCHIVED', name='project_status_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('projects', 'owner_id')
    op.alter_column('orders', 'delivery_status',
               existing_type=postgresql.ENUM('PENDING', 'ORDERED', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='delivery_status_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_index('idx_items_labor_type', table_name='items')
    op.alter_column('items', 'labor_type',
               existing_type=postgresql.ENUM('DEMOLITION', 'STRUCTURAL', 'FACADE', 'EXTERIOR_JOINERY', 'PLASTERING', 'PLUMBING', 'ELECTRICAL', 'WALL_COVERING', 'INTERIOR_JOINERY', 'LANDSCAPING', 'PRICE_REVISION', name='work_type_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_constraint(None, 'edit_history', type_='foreignkey')
    op.drop_index('idx_edit_history_user', table_name='edit_history')
    op.alter_column('edit_history', 'source',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('edit_history', 'user_id')
    op.alter_column('comments', 'role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('approvals', 'status',
               existing_type=postgresql.ENUM('APPROVED', 'REJECTED', 'CHANGE_ORDER', 'PENDING', 'SUPPLIED_BY', name='approval_status_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('approvals', 'role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index('idx_quotes_status', table_name='quotes')
    op.drop_index('idx_quotes_project_status', table_name='quotes')
    op.drop_index('idx_quotes_project', table_name='quotes')
    op.drop_index('idx_quotes_created', table_name='quotes')
    op.drop_table('quotes')
    op.drop_index('idx_project_members_user', table_name='project_members')
    op.drop_index('idx_project_members_role', table_name='project_members')
    op.drop_index('idx_project_members_project_role', table_name='project_members')
    op.drop_index('idx_project_members_project', table_name='project_members')
    op.drop_table('project_members')
    op.drop_index('idx_users_zulip_user_id', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
