"""Initial schema

Revision ID: 7ce0440880d9
Revises: 
Create Date: 2025-12-18 13:05:57.336392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ce0440880d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('devis_status', sa.String(length=50), nullable=True),
    sa.Column('invoice_count', sa.Integer(), nullable=False),
    sa.Column('percentage_paid', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('has_data', sa.Boolean(), nullable=False),
    sa.CheckConstraint("devis_status IS NULL OR devis_status IN ('sent', 'approved', 'rejected')", name='projects_devis_status_valid'),
    sa.CheckConstraint("status IN ('draft', 'ready', 'active', 'completed', 'archived')", name='projects_status_valid'),
    sa.CheckConstraint('LENGTH(id) > 0 AND LENGTH(id) <= 50', name='projects_id_length'),
    sa.CheckConstraint('LENGTH(name) > 0 AND LENGTH(name) <= 255', name='projects_name_length'),
    sa.CheckConstraint('invoice_count >= 0', name='projects_invoice_count_valid'),
    sa.CheckConstraint('percentage_paid >= 0 AND percentage_paid <= 100', name='projects_percentage_paid_valid'),
    sa.CheckConstraint('start_date IS NULL OR end_date IS NULL OR start_date <= end_date', name='projects_date_range_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_created', 'projects', ['created_at'], unique=False)
    op.create_index('idx_projects_dates', 'projects', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_projects_status', 'projects', ['status'], unique=False)
    op.create_table('workers',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workers_name', 'workers', ['name'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('LENGTH(id) > 0 AND LENGTH(id) <= 50', name='sections_id_length'),
    sa.CheckConstraint('LENGTH(label) > 0 AND LENGTH(label) <= 255', name='sections_label_length'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sections_project', 'sections', ['project_id'], unique=False)
    op.create_table('worker_jobs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('worker_id', sa.String(length=50), nullable=False),
    sa.Column('chantier_name', sa.String(length=255), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_worker_jobs_chantier', 'worker_jobs', ['chantier_name'], unique=False)
    op.create_index('idx_worker_jobs_dates', 'worker_jobs', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_worker_jobs_worker', 'worker_jobs', ['worker_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.String(length=50), nullable=False),
    sa.Column('product', sa.Text(), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('supplier_link', sa.Text(), nullable=True),
    sa.Column('labor_type', sa.String(length=50), nullable=True),
    sa.Column('price_ttc', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_ht_quote', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('LENGTH(TRIM(product)) > 0', name='items_product_not_empty'),
    sa.CheckConstraint('price_ht_quote IS NULL OR price_ht_quote >= 0', name='items_price_ht_valid'),
    sa.CheckConstraint('price_ttc IS NULL OR price_ttc >= 0', name='items_price_ttc_valid'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'product', name='uq_items_section_product')
    )
    op.create_index('idx_items_product', 'items', ['product'], unique=False)
    op.create_index('idx_items_section', 'items', ['section_id'], unique=False)
    op.create_index('idx_items_updated', 'items', ['updated_at'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('client', 'cray')", name='approvals_role_valid'),
    sa.CheckConstraint("status IS NULL OR status IN ('approved', 'rejected', 'change_order', 'pending', 'supplied_by')", name='approvals_status_valid'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'role', name='uq_approvals_item_role')
    )
    op.create_index('idx_approvals_item', 'approvals', ['item_id'], unique=False)
    op.create_index('idx_approvals_item_role', 'approvals', ['item_id', 'role'], unique=False)
    op.create_index('idx_approvals_status', 'approvals', ['status'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'role', name='uq_comments_item_role')
    )
    op.create_index('idx_comments_item', 'comments', ['item_id'], unique=False)
    op.create_table('custom_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'field_name', name='uq_custom_fields_item_field')
    )
    op.create_index('idx_custom_fields_item', 'custom_fields', ['item_id'], unique=False)
    op.create_table('edit_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.String(length=50), nullable=True),
    sa.Column('section_label', sa.String(length=255), nullable=True),
    sa.Column('product', sa.Text(), nullable=True),
    sa.Column('field_path', sa.String(length=255), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('manual', 'agent')", name='edit_history_source_valid'),
    sa.CheckConstraint('LENGTH(field_path) > 0 AND LENGTH(field_path) <= 255', name='edit_history_field_path_length'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_edit_history_item', 'edit_history', ['item_id'], unique=False)
    op.create_index('idx_edit_history_timestamp', 'edit_history', ['timestamp'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('ordered', sa.Boolean(), nullable=False),
    sa.Column('order_date', sa.String(length=10), nullable=True),
    sa.Column('delivery_date', sa.String(length=10), nullable=True),
    sa.Column('delivery_status', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(order_date IS NULL OR order_date ~ '^\\d{2}/\\d{2}$') AND (delivery_date IS NULL OR delivery_date ~ '^\\d{2}/\\d{2}$')", name='orders_date_format'),
    sa.CheckConstraint('quantity IS NULL OR quantity > 0', name='orders_quantity_valid'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_index('idx_orders_item', 'orders', ['item_id'], unique=False)
    op.create_index('idx_orders_ordered', 'orders', ['ordered'], unique=False)
    op.create_table('replacement_urls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_replacement_urls_approval', 'replacement_urls', ['approval_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_replacement_urls_approval', table_name='replacement_urls')
    op.drop_table('replacement_urls')
    op.drop_index('idx_orders_ordered', table_name='orders')
    op.drop_index('idx_orders_item', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_edit_history_timestamp', table_name='edit_history')
    op.drop_index('idx_edit_history_item', table_name='edit_history')
    op.drop_table('edit_history')
    op.drop_index('idx_custom_fields_item', table_name='custom_fields')
    op.drop_table('custom_fields')
    op.drop_index('idx_comments_item', table_name='comments')
    op.drop_table('comments')
    op.drop_index('idx_approvals_status', table_name='approvals')
    op.drop_index('idx_approvals_item_role', table_name='approvals')
    op.drop_index('idx_approvals_item', table_name='approvals')
    op.drop_table('approvals')
    op.drop_index('idx_items_updated', table_name='items')
    op.drop_index('idx_items_section', table_name='items')
    op.drop_index('idx_items_product', table_name='items')
    op.drop_table('items')
    op.drop_index('idx_worker_jobs_worker', table_name='worker_jobs')
    op.drop_index('idx_worker_jobs_dates', table_name='worker_jobs')
    op.drop_index('idx_worker_jobs_chantier', table_name='worker_jobs')
    op.drop_table('worker_jobs')
    op.drop_index('idx_sections_project', table_name='sections')
    op.drop_table('sections')
    op.drop_index('idx_workers_name', table_name='workers')
    op.drop_table('workers')
    op.drop_index('idx_projects_status', table_name='projects')
    op.drop_index('idx_projects_dates', table_name='projects')
    op.drop_index('idx_projects_created', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
